### PR TITLE
Add n-elie as a maintainer

### PR DESCRIPTION
**Pull request by klauer**
Adding @n-elie as a maintainer, pending their agreement.

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
@n-elie, please confirm that you accept to be a maintainer

**Comment by n-elie** [comment]
@hhslepicka Yes, I accept to be a maintainer

**Comment by klauer** [comment]
Welcome to the party, @n-elie 🎉

**Pull request merged**
